-- ============================================================================
-- Link generated transactions back to the recurring rule that created them
-- ============================================================================
-- ON DELETE SET NULL (not RESTRICT/CASCADE): deleting a recurring rule must
-- not destroy the real transaction history it already generated. Those rows
-- stay as ordinary transactions, just no longer tagged to a rule.
alter table public.transactions
  add column if not exists recurring_id uuid references public.recurring_transactions (id) on delete set null;

comment on column public.transactions.recurring_id is
  'Set when this transaction was auto-generated by generate_due_recurring_transactions().';

create index if not exists transactions_recurring_id_idx
  on public.transactions (recurring_id);

-- Prevents generate_due_recurring_transactions() from ever creating two
-- transactions for the same rule on the same date, including on concurrent
-- or repeated runs the same day.
create unique index if not exists transactions_recurring_id_date_unique
  on public.transactions (recurring_id, date)
  where recurring_id is not null;
